### ISSUE TITLE
qBittorrent plugin does not have python in its path so that search plugins cannot be used

### ISSUE THREAD

**Issue by jarmo** [freenas/iocage-ports#40]
Basically, when using [qBittorrent plugin](https://github.com/freenas/iocage-ports/tree/master/net-p2p/qbittorrent) then trying to use its search functionality is not possible since it needs Python and this isn't in the path for web-UI.

I solved it like this:

* Created a symlink to python3, since it seems to be something what [qBittorrent looks for](https://github.com/qbittorrent/qBittorrent/blob/f86c5442aa84737db7837ae9803647451714c6f2/src/base/utils/foreignapps.cpp#L253-L264):
```
$ ln -s /usr/local/bin/python3.6 /usr/local/bin/python3
```

* Modified `/etc/rc.local` to change **PATH**:
```
export PATH="$PATH:/usr/local/bin"
/usr/local/bin/qbittorrent-nox -d
```

Would be nice if everything works out-of-the-box.

**Comment by miwi-fbsd** [comment]
will be fixed with the next plugin release.

**Comment by andreas-ateles** [comment]
This is still broken, @miwi-fbsd.

`python3` is in `/usr/local/bin`, but `/usr/local/bin` is not in the path. So still need to add the `export PATH="$PATH:/usr/local/bin"` line like @jarmo said. With that addition it works. Thanks!

**Comment by jarmo** [comment]
@andreas-ateles that's great that I helped you. @miwi-fbsd Should this issue be reopened then or has there not been any release so far? Even if there has not been any releases yet then I would keep it open so it would be easier to find.

**Comment by kmoore134** [comment]
We don't really update this repo any more, so any fixes to ports will need to be re-directed to FreeBSD's upstream ports repository.

https://bugs.freebsd.org/bugzilla/

**Comment by jarmo** [comment]
@kmoore134 why not add a statement into the README and archive this repo then in GitHub so that it would be a clear sign of inactive repository? Would be clear and straight-forward.
