### ISSUE TITLE
qBittorrent installation should show default web-UI login credentials

### ISSUE THREAD

**Issue by jarmo** [freenas/iocage-ports#41]
A message is shown after installing qBittorrent plugin through FreeNAS about the location of the qBittorrent web-UI. However, nothing is shown about default login credentials - it would be much better to show `admin:adminadmin` for default credentials to avoid extra time for googling.

**Comment by miwi-fbsd** [comment]
Fixed for 11.3 https://github.com/freenas/iocage-plugin-qbittorrent/blob/master/post_install.sh#L12

Thank you for the report.
